// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsUA.API.Data;

#nullable disable

namespace NewsUA.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsUA.API.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Author name 1",
                            HotStatus = "Basic",
                            Information = "Information 1",
                            PublishedAt = new DateTime(2023, 5, 15, 16, 3, 49, 175, DateTimeKind.Local).AddTicks(6640),
                            Status = "InProcess",
                            SubTitle = "SubTitle 1",
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Author name 2",
                            HotStatus = "Hot",
                            Information = "Information 2",
                            PublishedAt = new DateTime(2023, 5, 15, 16, 3, 49, 175, DateTimeKind.Local).AddTicks(6711),
                            Status = "InProcess",
                            SubTitle = "SubTitle 2",
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Author name 3",
                            HotStatus = "Basic",
                            Information = "Information 3",
                            PublishedAt = new DateTime(2023, 5, 15, 16, 3, 49, 175, DateTimeKind.Local).AddTicks(6715),
                            Status = "InProcess",
                            SubTitle = "SubTitle 3",
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Author name 4",
                            HotStatus = "Basic",
                            Information = "Information 4",
                            PublishedAt = new DateTime(2023, 5, 15, 16, 3, 49, 175, DateTimeKind.Local).AddTicks(6720),
                            Status = "InProcess",
                            SubTitle = "SubTitle 4",
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Author name 5",
                            HotStatus = "Basic",
                            Information = "Information 5",
                            PublishedAt = new DateTime(2023, 5, 15, 16, 3, 49, 175, DateTimeKind.Local).AddTicks(6724),
                            Status = "InProcess",
                            SubTitle = "SubTitle 5",
                            Title = "Title 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
